# Project 01 — Data collection and first profiling

## First-Time Buyer Affordability Pressure by Area

This notebook records the first data collection and profiling stage for the project. The source review establishes whether the official affordability workbook is suitable for analysis before findings are produced.

The workflow downloads the official ONS workbook into `data/raw/`, keeps the raw file separate from cleaned outputs, and performs first-pass profiling checks.

## Source collection

The raw workbook is collected from the ONS current dataset endpoint and stored in `data/raw/`. Raw files remain unchanged; cleaned outputs are saved separately.

In [1]:
from pathlib import Path
from urllib.parse import quote
from urllib.request import Request, urlopen
from datetime import date
import re
import shutil

import pandas as pd
import numpy as np

In [2]:
PROJECT_ROOT = Path("..").resolve()
RAW_DIR = PROJECT_ROOT / "data" / "raw"
CLEANED_DIR = PROJECT_ROOT / "data" / "cleaned"
RAW_FILE = RAW_DIR / "aff1ratioofhousepricetoworkplacebasedearnings.xlsx"

RAW_DIR.mkdir(parents=True, exist_ok=True)
CLEANED_DIR.mkdir(parents=True, exist_ok=True)

ONS_PATH = (
    "/peoplepopulationandcommunity/housing/datasets/"
    "ratioofhousepricetoworkplacebasedearningslowerquartileandmedian/"
    "current/aff1ratioofhousepricetoworkplacebasedearnings.xlsx"
)
SOURCE_URL = "https://www.ons.gov.uk/file?uri=" + quote(ONS_PATH, safe="")

def download_file(url, output_path):
    request = Request(
        url,
        headers={
            "User-Agent": "Mozilla/5.0",
            "Accept": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/octet-stream,*/*",
        },
    )
    with urlopen(request) as response, open(output_path, "wb") as output_file:
        shutil.copyfileobj(response, output_file)

if RAW_FILE.exists():
    print("Raw workbook already exists. Download skipped.")
else:
    print("Downloading ONS workbook...")
    download_file(SOURCE_URL, RAW_FILE)
    print("Download complete.")

source_record = pd.DataFrame([{
    "source_name": "ONS House price to workplace-based earnings ratio",
    "source_url": SOURCE_URL,
    "local_file": str(RAW_FILE.relative_to(PROJECT_ROOT)),
    "download_checked_on": date.today().isoformat(),
    "file_size_mb": round(RAW_FILE.stat().st_size / (1024 * 1024), 2),
}])

source_record

Downloading ONS workbook...
Download complete.

,source_name,source_url,local_file,download_checked_on,file_size_mb
0,ONS House price to workplace-based earnings ratio,https://www.ons.gov.uk/file?uri=%2Fpeoplepopul...,data\raw\aff1ratioofhousepricetoworkplacebased...,2026-06-29,0.49

## Workbook inspection

ONS workbooks often include cover sheets, notes and metadata. The workbook structure is inspected before the data table is selected.

In [3]:
excel_file = pd.ExcelFile(RAW_FILE)

sheet_overview = pd.DataFrame({
    "sheet_number": range(1, len(excel_file.sheet_names) + 1),
    "sheet_name": excel_file.sheet_names,
})

sheet_overview

    sheet_number            sheet_name
0              1              Contents
1              2              Metadata
2              3  Terms and Conditions
3              4                    1a
4              5                    1b
5              6                    1c
6              7                    2a
7              8                    2b
8              9                    2c
9             10                    3a
10            11                    3b
11            12                    3c
12            13                    4a
13            14                    4b
14            15                    4c
15            16                    5a
16            17                    5b
17            18                    5c
18            19                    6a
19            20                    6b
20            21                    6c

In [4]:
for sheet_name in excel_file.sheet_names:
    print("\n" + "=" * 80)
    print(f"Sheet: {sheet_name}")
    print("=" * 80)
    preview = pd.read_excel(RAW_FILE, sheet_name=sheet_name, header=None, nrows=12)
    display(preview)

================================================================================
Sheet: Contents
================================================================================

,0,1
0,Contents,NaN
1,Metadata,Information on the ratio of house price to wor...
2,Terms and Conditions,Terms and conditions
3,Country and region - Median,NaN
4,Table 1a (Median house price),"Median house price by country and region, Engl..."
5,Table 1b (Median earnings),Median gross annual workplace-based earnings b...
6,Table 1c (Median affordability ratio),Ratio of median house price to median gross an...
7,Country and region - Lower quartile,NaN
8,Table 2a (Lower quartile house price),Lower quartile house price by country and regi...
9,Table 2b (Lower quartile earnings),Lower quartile gross annual workplace-based ea...
10,Table 2c (Lower quartile affordability ratio),Ratio of lower quartile house price to lower q...
11,County - Median,NaN

================================================================================
Sheet: Metadata
================================================================================

                                                    0
0                                            Metadata
1   Affordability ratios calculated by dividing ho...
2   For detailed information on aspects of the qua...
3      Housing affordability in England and Wales QMI
4                                            Earnings
5   Earnings data are taken from the Annual Survey...
6   • full-time earnings;\n• annual earnings where...
7   Annual estimates  of earnings are based on the...
8   For detailed information on aspects of the qua...
9   Annual Survey of Hours and Earnings, Low pay a...
10                                       House prices
11  These data are part of the House Price Statist...

================================================================================
Sheet: Terms and Conditions
================================================================================

                                                    0
0                                Terms and Conditions
1                                            About us
2   The Office for National Statistics (ONS) is th...
3   The Director General of ONS reports directly t...
4                         Copyright and reproduction
5                              © Crown copyright 2026
6   You may re-use this information (not including...
7   These statistics were adapted from data from t...
8         To view the Open Government licence, go to:
9   www.nationalarchives.gov.uk/doc/open-governmen...
10  To write to the Information Policy Team write ...
11                 email: psi@nationalarchives.gov.uk

================================================================================
Sheet: 1a
================================================================================

,0,1,2,3,4,5,6,7,8,9,...,21,22,23,24,25,26,27,28,29,30
0,Table 1a - Median house price by country and r...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Code,Name,Year ending Sep 1997,Year ending Sep 1998,Year ending Sep 1999,Year ending Sep 2000,Year ending Sep 2001,Year ending Sep 2002,Year ending Sep 2003,Year ending Sep 2004,...,Year ending Sep 2016,Year ending Sep 2017,Year ending Sep 2018,Year ending Sep 2019,Year ending Sep 2020,Year ending Sep 2021,Year ending Sep 2022,Year ending Sep 2023,Year ending Sep 2024,Year ending Sep 2025
2,K04000001,England and Wales,59950,64500,70000,78500,87950,104000,125000,145500,...,215000,225000,233000,236000,246995,280000,280000,290000,289995,295000
3,E92000001,England,59995,65000,71000,79995,89950,106000,127500,148000,...,220000,230000,239950,242000,250000,285000,285000,297500,295000,300000
4,W92000004,Wales,47000,49000,52000,56000,59950,67500,82500,109000,...,148000,150000,156000,160000,167000,187500,197000,202000,209995,213000
5,E12000001,North East,46500,47500,50000,52000,53800,59500,72000,92000,...,133500,135000,139995,142000,145000,160000,155000,165995,167500,172000
6,E12000002,North West,48500,50000,52500,56000,59950,67500,80000,100950,...,148000,155000,160000,165000,174000,199000,200000,210000,215000,221000
7,E12000003,Yorkshire and The Humber,48500,49950,52000,55000,59000,66995,82500,105000,...,149950,155000,160000,164950,170000,190000,190000,204950,207000,215000
8,E12000004,East Midlands,49950,53000,56000,60000,68000,79995,99950,123000,...,165250,176995,186000,192500,200000,228000,236995,248000,245000,250000
9,E12000005,West Midlands,54000,56000,59950,65500,73500,85000,103000,125000,...,168000,178000,188000,195000,202992.5,230000,233000,245000,245000,252000
10,E12000006,East of England,62000,67750,73995,84000,95500,118500,140000,159995,...,250000,275000,284995,287500,295000,325000,335000,349995,340000,348000
11,E12000007,London,83500,94950,111000,134000,150000,174000,195000,217000,...,435000,460000,467500,470000,485000,511000,520000,526000,530000,527000

================================================================================
Sheet: 1b
================================================================================

,0,1,2,3,4,5,6,7,8,9,...,21,22,23,24,25,26,27,28,29,30
0,Table 1b - Median gross annual workplace-based...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Code,Name,1997.0,1998.0,1999.0,2000.0,2001.0,2002.0,2003.0,2004.0,...,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0,2023.0,2024.0,2025.0
2,K04000001,England and Wales,16885.0,17631.0,17974.0,19000.0,19898.0,20562.0,21359.0,22284.0,...,28325.0,28939.0,29667.0,30526.0,31605.0,31300.0,33133.0,35045.0,37482.0,39059.0
3,E92000001,England,16958.0,17709.0,17939.0,19107.0,19997.0,20706.0,21500.0,22418.0,...,28496.0,29083.0,29856.0,30704.0,31791.0,31440.0,33280.0,35217.0,37647.0,39298.0
4,W92000004,Wales,15679.0,16118.0,16457.0,17157.0,18018.0,18189.0,19130.0,20085.0,...,25440.0,26026.0,26353.0,27466.0,28387.0,28527.0,30630.0,32363.0,34267.0,35796.0
5,E12000001,North East,15622.0,15778.0,16282.0,17430.0,17844.0,18076.0,18228.0,19247.0,...,25561.0,25904.0,26355.0,27234.0,27833.0,27560.0,29519.0,31104.0,33008.0,34403.0
6,E12000002,North West,16107.0,16587.0,16977.0,17863.0,18567.0,19234.0,19916.0,20717.0,...,26220.0,26754.0,27376.0,28175.0,29459.0,29371.0,30698.0,33078.0,35176.0,37361.0
7,E12000003,Yorkshire and The Humber,15538.0,16368.0,16527.0,17503.0,18270.0,18863.0,19659.0,20433.0,...,25946.0,26309.0,26892.0,27879.0,28709.0,28732.0,30354.0,31921.0,34423.0,35682.0
8,E12000004,East Midlands,15773.0,16279.0,16392.0,17352.0,18291.0,19125.0,19847.0,20691.0,...,25474.0,25882.0,26711.0,28044.0,29043.0,28363.0,30345.0,31680.0,33891.0,35600.0
9,E12000005,West Midlands,15878.0,16718.0,17000.0,17812.0,18756.0,19225.0,19786.0,20765.0,...,26352.0,26837.0,27682.0,28549.0,29628.0,29893.0,31545.0,33342.0,34940.0,37064.0
10,E12000006,East of England,16858.0,17584.0,18000.0,19020.0,19978.0,20495.0,21511.0,22242.0,...,27892.0,28456.0,29153.0,30350.0,31016.0,30735.0,32615.0,34865.0,36972.0,38597.0
11,E12000007,London,20871.0,21862.0,22487.0,24204.0,25215.0,26467.0,27455.0,28750.0,...,36170.0,37171.0,38146.0,39013.0,40994.0,39737.0,41987.0,44681.0,47441.0,49692.0

================================================================================
Sheet: 1c
================================================================================

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
0,Table 1c - Ratio of median house price to medi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Code,Name,1997.00,1998.00,1999.00,2000.00,2001.00,2002.00,2003.00,2004.00,...,2017.00,2018.00,2019.00,2020.00,2021.00,2022.00,2023.00,2024.00,2025.00,5-Year Average
2,K04000001,England and Wales,3.55,3.66,3.89,4.13,4.42,5.06,5.85,6.53,...,7.77,7.85,7.73,7.82,8.95,8.45,8.28,7.74,7.55,8.19
3,E92000001,England,3.54,3.67,3.96,4.19,4.50,5.12,5.93,6.60,...,7.91,8.04,7.88,7.86,9.06,8.56,8.45,7.84,7.63,8.31
4,W92000004,Wales,3.00,3.04,3.16,3.26,3.33,3.71,4.31,5.43,...,5.76,5.92,5.83,5.88,6.57,6.43,6.24,6.13,5.95,6.26
5,E12000001,North East,2.98,3.01,3.07,2.98,3.02,3.29,3.95,4.78,...,5.21,5.31,5.21,5.21,5.81,5.25,5.34,5.07,5.00,5.29
6,E12000002,North West,3.01,3.01,3.09,3.13,3.23,3.51,4.02,4.87,...,5.79,5.84,5.86,5.91,6.78,6.52,6.35,6.11,5.92,6.34
7,E12000003,Yorkshire and The Humber,3.12,3.05,3.15,3.14,3.23,3.55,4.20,5.14,...,5.89,5.95,5.92,5.92,6.61,6.26,6.42,6.01,6.03,6.27
8,E12000004,East Midlands,3.17,3.26,3.42,3.46,3.72,4.18,5.04,5.94,...,6.84,6.96,6.86,6.89,8.04,7.81,7.83,7.23,7.02,7.59
9,E12000005,West Midlands,3.40,3.35,3.53,3.68,3.92,4.42,5.21,6.02,...,6.63,6.79,6.83,6.85,7.69,7.39,7.35,7.01,6.80,7.25
10,E12000006,East of England,3.68,3.85,4.11,4.42,4.78,5.78,6.51,7.19,...,9.66,9.78,9.47,9.51,10.57,10.27,10.04,9.20,9.02,9.82
11,E12000007,London,4.00,4.34,4.94,5.54,5.95,6.57,7.10,7.55,...,12.38,12.26,12.05,11.83,12.86,12.38,11.77,11.17,10.61,11.76

================================================================================
Sheet: 2a
================================================================================

,0,1,2,3,4,5,6,7,8,9,...,21,22,23,24,25,26,27,28,29,30
0,Table 2a - Lower quartile house price by count...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Code,Name,Year ending Sep 1997,Year ending Sep 1998,Year ending Sep 1999,Year ending Sep 2000,Year ending Sep 2001,Year ending Sep 2002,Year ending Sep 2003,Year ending Sep 2004,...,Year ending Sep 2016,Year ending Sep 2017,Year ending Sep 2018,Year ending Sep 2019,Year ending Sep 2020,Year ending Sep 2021,Year ending Sep 2022,Year ending Sep 2023,Year ending Sep 2024,Year ending Sep 2025
2,K04000001,England and Wales,42500,45000,48000,52000,57000,65000,79000,98000,...,141999,147000,152000,155000,162000,185000,182500,190000,192000,200000
3,E92000001,England,43000,45000,48500,53000,58500,67000,80000,100000,...,145000,150000,156000,160000,165000,189950,186250,195712,196995,204995
4,W92000004,Wales,35000,35875,37000,39000,40500,45000,55000,73950,...,105500,109000,112500,116500,120000,134000,140000,145000,148000,155000
5,E12000001,North East,32000,32000,33000,34000,34500,36000,43000,59950,...,89000,90000,93000,95000,95000,107000,105000,111000,115000,120000
6,E12000002,North West,34450,35000,36000,37350,38500,41950,49500,66000,...,104000,109631,112000,116000,120000,138500,137500,145000,149995,155500
7,E12000003,Yorkshire and The Humber,35000,35500,37000,38500,39750,42500,52500,70000,...,105995,110000,115000,117500,120000,135000,135000,143280,146000,152575
8,E12000004,East Midlands,37000,38500,40000,43000,47000,56000,71950,89000,...,125000,130995,139500,143000,149000,168000,175000,181500,182000,185550
9,E12000005,West Midlands,40000,41000,43500,46000,51000,59500,73000,89950,...,125000,130000,139000,144995,150000,168000,170000,180000,180000,190000
10,E12000006,East of England,45000,48000,52500,59950,69000,83000,104000,121000,...,180000,199500,209950,213000,220000,240000,246000,255000,250000,255000
11,E12000007,London,59500,66995,76000,91000,109000,128000,150000,165500,...,325000,345000,350000,355000,364000,385000,385000,395000,392000,400000

================================================================================
Sheet: 2b
================================================================================

,0,1,2,3,4,5,6,7,8,9,...,21,22,23,24,25,26,27,28,29,30
0,Table 2b - Lower quartile gross annual workpla...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Code,Name,1997.0,1998.0,1999.0,2000.0,2001.0,2002.0,2003.0,2004.0,...,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0,2023.0,2024.0,2025.0
2,K04000001,England and Wales,12016.0,12533.0,12844.0,13700.0,14265.0,14742.0,15260.0,15866.0,...,20130.0,20554.0,21157.0,21979.0,22847.0,22906.0,24347.0,26085.0,27999.0,29270.0
3,E92000001,England,12058.0,12606.0,12852.0,13778.0,14337.0,14852.0,15364.0,15948.0,...,20252.0,20651.0,21263.0,22052.0,22965.0,23000.0,24440.0,26165.0,28074.0,29359.0
4,W92000004,Wales,11124.0,11526.0,11751.0,12567.0,13045.0,13188.0,13751.0,14533.0,...,18544.0,19124.0,19690.0,20447.0,21045.0,21635.0,23100.0,24742.0,26320.0,27865.0
5,E12000001,North East,11197.0,11395.0,11736.0,12663.0,12867.0,13174.0,13554.0,14020.0,...,18866.0,19451.0,19544.0,20387.0,20861.0,21001.0,22232.0,23829.0,25630.0,27082.0
6,E12000002,North West,11542.0,11876.0,12200.0,12856.0,13389.0,13860.0,14289.0,14894.0,...,19003.0,19526.0,19963.0,20639.0,21479.0,21750.0,22884.0,25000.0,26729.0,27992.0
7,E12000003,Yorkshire and The Humber,11275.0,11740.0,12012.0,12787.0,13162.0,13725.0,14328.0,14865.0,...,18834.0,19209.0,19793.0,20579.0,21264.0,21388.0,22953.0,24559.0,26522.0,27690.0
8,E12000004,East Midlands,11448.0,11714.0,11961.0,12749.0,13288.0,13818.0,14412.0,14814.0,...,18690.0,18968.0,19581.0,20533.0,21436.0,21530.0,23000.0,24257.0,26203.0,27413.0
9,E12000005,West Midlands,11515.0,12037.0,12332.0,13044.0,13618.0,13901.0,14456.0,15045.0,...,19126.0,19453.0,20080.0,20994.0,21817.0,22041.0,23452.0,25245.0,26576.0,27951.0
10,E12000006,East of England,12251.0,12669.0,13086.0,13859.0,14439.0,14965.0,15587.0,16044.0,...,20189.0,20338.0,21091.0,22108.0,22724.0,23030.0,24249.0,26295.0,27901.0,29110.0
11,E12000007,London,15022.0,15653.0,16090.0,17362.0,18210.0,18689.0,19759.0,20496.0,...,25381.0,26000.0,26930.0,27381.0,28854.0,28441.0,30064.0,31731.0,34330.0,35424.0

================================================================================
Sheet: 2c
================================================================================

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
0,Table 2c - Ratio of lower quartile house price...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Code,Name,1997.00,1998.00,1999.00,2000.00,2001.00,2002.00,2003.00,2004.00,...,2017.00,2018.00,2019.00,2020.00,2021.00,2022.00,2023.00,2024.00,2025.00,5-Year Average
2,K04000001,England and Wales,3.54,3.59,3.74,3.80,4.00,4.41,5.18,6.18,...,7.15,7.18,7.05,7.09,8.08,7.50,7.28,6.86,6.83,7.31
3,E92000001,England,3.57,3.57,3.77,3.85,4.08,4.51,5.21,6.27,...,7.26,7.34,7.26,7.18,8.26,7.62,7.48,7.02,6.98,7.47
4,W92000004,Wales,3.15,3.11,3.15,3.10,3.10,3.41,4.00,5.09,...,5.70,5.71,5.70,5.70,6.19,6.06,5.86,5.62,5.56,5.86
5,E12000001,North East,2.86,2.81,2.81,2.68,2.68,2.73,3.17,4.28,...,4.63,4.76,4.66,4.55,5.09,4.72,4.66,4.49,4.43,4.68
6,E12000002,North West,2.98,2.95,2.95,2.91,2.88,3.03,3.46,4.43,...,5.61,5.61,5.62,5.59,6.37,6.01,5.80,5.61,5.56,5.87
7,E12000003,Yorkshire and The Humber,3.10,3.02,3.08,3.01,3.02,3.10,3.66,4.71,...,5.73,5.81,5.71,5.64,6.31,5.88,5.83,5.50,5.51,5.81
8,E12000004,East Midlands,3.23,3.29,3.34,3.37,3.54,4.05,4.99,6.01,...,6.91,7.12,6.96,6.95,7.80,7.61,7.48,6.95,6.77,7.32
9,E12000005,West Midlands,3.47,3.41,3.53,3.53,3.75,4.28,5.05,5.98,...,6.68,6.92,6.91,6.88,7.62,7.25,7.13,6.77,6.80,7.11
10,E12000006,East of England,3.67,3.79,4.01,4.33,4.78,5.55,6.67,7.54,...,9.81,9.95,9.63,9.68,10.42,10.14,9.70,8.96,8.76,9.6
11,E12000007,London,3.96,4.28,4.72,5.24,5.99,6.85,7.59,8.07,...,13.27,13.00,12.97,12.62,13.54,12.81,12.45,11.42,11.29,12.3

================================================================================
Sheet: 3a
================================================================================

,0,1,2,3,4,5,6,7,8,9,...,21,22,23,24,25,26,27,28,29,30
0,"Table 3a - Median house price by county, Engla...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Code,Name,Year ending Sep 1997,Year ending Sep 1998,Year ending Sep 1999,Year ending Sep 2000,Year ending Sep 2001,Year ending Sep 2002,Year ending Sep 2003,Year ending Sep 2004,...,Year ending Sep 2016,Year ending Sep 2017,Year ending Sep 2018,Year ending Sep 2019,Year ending Sep 2020,Year ending Sep 2021,Year ending Sep 2022,Year ending Sep 2023,Year ending Sep 2024,Year ending Sep 2025
2,E10000003,Cambridgeshire,66000,71500,79000,88000,102500,123000,143000,160000,...,260000,284250,290000,299995,310000,328498,342500,361000,350000,350000
3,E10000007,Derbyshire,49000,50000,54950,57000,60000,72000,90000,115000,...,157000,166000,174995,180000,185000,212500,222000,235000,230000,235000
4,E10000008,Devon,60000,65000,69500,80000,92000,118950,147000,169000,...,229000,240000,250000,254950,265000,290000,310000,324995,312000,310000
5,E10000011,East Sussex,63000,69950,76000,87000,99000,124500,148000,167000,...,250000,267000,278000,280000,295000,330000,342995,350000,345000,340000
6,E10000012,Essex,65000,71000,77500,88000,104995,125000,150000,169950,...,270000,298000,310000,315000,318500,350000,360000,370000,365000,375000
7,E10000013,Gloucestershire,61000,67000,74000,84500,97000,114500,136000,157000,...,222500,240000,250000,255000,265000,299995,299950,320000,315500,315000
8,E10000014,Hampshire,74950,83950,90000,110000,125000,144995,169950,185000,...,280000,302000,312000,315000,322000,350000,365000,370000,367500,367000
9,E10000015,Hertfordshire,81000,92000,102000,120000,135000,156500,182000,199950,...,351500,377500,387200,387500,405000,435000,445000,451000,450000,455000
10,E10000016,Kent,63500,69950,75000,87000,100000,120000,143500,163500,...,257000,278000,290000,295000,302500,336000,350000,357500,345000,350000
11,E10000017,Lancashire,48500,50000,52000,55000,57950,63000,75950,96500,...,145000,150000,150000,155000,162500,182500,180000,192500,195000,198000

================================================================================
Sheet: 3b
================================================================================

,0,1,2,3,4,5,6,7,8,9,...,21,22,23,24,25,26,27,28,29,30
0,Table 3b - Median gross annual workplace-based...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Code,Name,1997.0,1998.0,1999.0,2000.0,2001.0,2002.0,2003.0,2004.0,...,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0,2023.0,2024.0,2025.0
2,E10000003,Cambridgeshire,17140.0,17777.0,17771.0,19269.0,20270.0,20684.0,22084.0,24009.0,...,30000.0,30404.0,31347.0,32369.0,32786.0,32415.0,33943.0,37784.0,39706.0,42323.0
3,E10000007,Derbyshire,15371.0,15653.0,15904.0,16494.0,17460.0,18126.0,19175.0,20281.0,...,25088.0,25950.0,26569.0,27380.0,28002.0,28118.0,29826.0,30689.0,33776.0,36011.0
4,E10000008,Devon,14203.0,14714.0,15079.0,16302.0,16841.0,17571.0,18738.0,19524.0,...,25377.0,24693.0,25860.0,26233.0,26843.0,27429.0,29771.0,30981.0,32627.0,34939.0
5,E10000011,East Sussex,15330.0,15982.0,16424.0,17369.0,18367.0,18536.0,19530.0,20404.0,...,24985.0,26735.0,27639.0,26721.0,26789.0,27076.0,29077.0,30116.0,32898.0,35557.0
6,E10000012,Essex,16858.0,17745.0,18074.0,19575.0,20717.0,20837.0,21670.0,22074.0,...,27277.0,28679.0,28653.0,30374.0,30886.0,30372.0,32084.0,34241.0,37562.0,38098.0
7,E10000013,Gloucestershire,16431.0,17245.0,17527.0,18790.0,19503.0,19647.0,20696.0,21153.0,...,27535.0,28481.0,29423.0,30000.0,29909.0,30006.0,32320.0,33545.0,35936.0,37598.0
8,E10000014,Hampshire,16838.0,18027.0,17957.0,19473.0,20800.0,21563.0,22273.0,23261.0,...,28984.0,29857.0,30971.0,31710.0,32650.0,33115.0,34236.0,36061.0,37500.0,39324.0
9,E10000015,Hertfordshire,18403.0,19530.0,20320.0,21175.0,22540.0,23313.0,24481.0,25129.0,...,30727.0,30992.0,32033.0,32739.0,33601.0,33834.0,35000.0,37673.0,39881.0,42775.0
10,E10000016,Kent,16138.0,16864.0,17164.0,18244.0,18789.0,19669.0,20792.0,21551.0,...,27002.0,27181.0,27635.0,29834.0,30372.0,29559.0,31410.0,33074.0,35469.0,36127.0
11,E10000017,Lancashire,16102.0,16775.0,16746.0,17648.0,18027.0,18806.0,19680.0,20000.0,...,26130.0,25965.0,26500.0,27443.0,28934.0,28012.0,29774.0,31712.0,33940.0,35779.0

================================================================================
Sheet: 3c
================================================================================

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
0,Table 3c - Ratio of median house price to medi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Code,Name,1997.00,1998.00,1999.00,2000.00,2001.00,2002.00,2003.00,2004.00,...,2017.00,2018.00,2019.00,2020.00,2021.00,2022.00,2023.00,2024.00,2025.00,5-Year Average
2,E10000003,Cambridgeshire,3.85,4.02,4.45,4.57,5.06,5.95,6.48,6.66,...,9.35,9.25,9.27,9.46,10.13,10.09,9.55,8.81,8.27,9.37
3,E10000007,Derbyshire,3.19,3.19,3.46,3.46,3.44,3.97,4.69,5.67,...,6.40,6.59,6.57,6.61,7.56,7.44,7.66,6.81,6.53,7.2
4,E10000008,Devon,4.22,4.42,4.61,4.91,5.46,6.77,7.85,8.66,...,9.72,9.67,9.72,9.87,10.57,10.41,10.49,9.56,8.87,9.98
5,E10000011,East Sussex,4.11,4.38,4.63,5.01,5.39,6.72,7.58,8.18,...,9.99,10.06,10.48,11.01,12.19,11.80,11.62,10.49,9.56,11.13
6,E10000012,Essex,3.86,4.00,4.29,4.50,5.07,6.00,6.92,7.70,...,10.39,10.82,10.37,10.31,11.52,11.22,10.81,9.72,9.84,10.62
7,E10000013,Gloucestershire,3.71,3.89,4.22,4.50,4.97,5.83,6.57,7.42,...,8.43,8.50,8.50,8.86,10.00,9.28,9.54,8.78,8.38,9.2
8,E10000014,Hampshire,4.45,4.66,5.01,5.65,6.01,6.72,7.63,7.95,...,10.11,10.07,9.93,9.86,10.57,10.66,10.26,9.80,9.33,10.12
9,E10000015,Hertfordshire,4.40,4.71,5.02,5.67,5.99,6.71,7.43,7.96,...,12.18,12.09,11.84,12.05,12.86,12.71,11.97,11.28,10.64,11.89
10,E10000016,Kent,3.93,4.15,4.37,4.77,5.32,6.10,6.90,7.59,...,10.23,10.49,9.89,9.96,11.37,11.14,10.81,9.73,9.69,10.55
11,E10000017,Lancashire,3.01,2.98,3.11,3.12,3.21,3.35,3.86,4.83,...,5.78,5.66,5.65,5.62,6.52,6.05,6.07,5.75,5.53,5.98

================================================================================
Sheet: 4a
================================================================================

,0,1,2,3,4,5,6,7,8,9,...,21,22,23,24,25,26,27,28,29,30
0,Table 4a - Lower quartile house price by count...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Code,Name,Year ending Sep 1997,Year ending Sep 1998,Year ending Sep 1999,Year ending Sep 2000,Year ending Sep 2001,Year ending Sep 2002,Year ending Sep 2003,Year ending Sep 2004,...,Year ending Sep 2016,Year ending Sep 2017,Year ending Sep 2018,Year ending Sep 2019,Year ending Sep 2020,Year ending Sep 2021,Year ending Sep 2022,Year ending Sep 2023,Year ending Sep 2024,Year ending Sep 2025
2,E10000003,Cambridgeshire,48000,51500,55500,62000,72000,85000,105000,121500,...,180000,197725,208000,215000,223000,238000,247000,263000,255000,255000
3,E10000007,Derbyshire,36000,37000,38950,40000,43500,49950,64500,82500,...,116522,124000,128000,132000,137000,155000,162000,170000,170000,172500
4,E10000008,Devon,45000,48000,51200,59500,68000,84250,108000,129000,...,172000,180000,188000,190000,199995,220000,230000,242000,235000,235500
5,E10000011,East Sussex,45000,48000,52950,59500,69000,85000,105000,124000,...,180000,197000,205000,215000,220000,250000,250000,255000,255000,257450
6,E10000012,Essex,48000,52000,57000,65500,75500,90000,115500,131500,...,200000,225000,235000,243000,245000,269995,275000,285000,280000,290000
7,E10000013,Gloucestershire,46500,49000,54000,59950,70000,81500,100000,119000,...,165000,175000,185000,190000,198000,220000,222000,240000,238000,236200
8,E10000014,Hampshire,56000,61000,67500,79950,90000,109950,129950,144000,...,210000,230000,240000,239950,245000,265000,269950,275000,275000,279998
9,E10000015,Hertfordshire,59500,67000,74000,86000,99500,117000,139995,157000,...,265000,285000,295000,293375,305000,325000,325000,333500,335000,340000
10,E10000016,Kent,47500,51000,55000,62995,72675,85000,106000,125927,...,190000,210000,222500,225000,230000,255000,261995,270000,265000,270000
11,E10000017,Lancashire,34500,35000,36000,37000,37500,39462,45000,59500,...,101000,104784,105000,110000,113000,127500,126000,132000,135000,140000

================================================================================
Sheet: 4b
================================================================================

,0,1,2,3,4,5,6,7,8,9,...,21,22,23,24,25,26,27,28,29,30
0,Table 4b - Lower quartile gross annual workpla...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Code,Name,1997.0,1998.0,1999.0,2000.0,2001.0,2002.0,2003.0,2004.0,...,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0,2023.0,2024.0,2025.0
2,E10000003,Cambridgeshire,12637.0,13253.0,13593.0,14392.0,15090.0,15333.0,16736.0,17673.0,...,22535.0,22288.0,22688.0,23454.0,24000.0,24160.0,25590.0,28080.0,29375.0,30549.0
3,E10000007,Derbyshire,11448.0,11208.0,11847.0,12154.0,12781.0,12892.0,14009.0,14434.0,...,18235.0,18636.0,19364.0,19679.0,21309.0,21816.0,22584.0,23632.0,26042.0,27094.0
4,E10000008,Devon,10456.0,10900.0,11241.0,12113.0,12598.0,12914.0,13474.0,14250.0,...,19165.0,18790.0,19709.0,20385.0,20508.0,21146.0,22223.0,23939.0,25773.0,27374.0
5,E10000011,East Sussex,11051.0,11756.0,12106.0,13389.0,13575.0,13957.0,14549.0,15136.0,...,18215.0,18578.0,19354.0,19567.0,20690.0,21405.0,23027.0,23614.0,26846.0,28325.0
6,E10000012,Essex,12058.0,12773.0,13065.0,14108.0,14735.0,15295.0,15498.0,16000.0,...,19673.0,20501.0,20959.0,22012.0,22606.0,23000.0,24222.0,25915.0,28372.0,28492.0
7,E10000013,Gloucestershire,11881.0,12789.0,13062.0,13945.0,14451.0,14941.0,15405.0,15404.0,...,20269.0,20834.0,22137.0,22015.0,21893.0,22191.0,23858.0,25561.0,27514.0,29220.0
8,E10000014,Hampshire,12121.0,12794.0,13105.0,14354.0,15206.0,15739.0,16423.0,16800.0,...,20940.0,21651.0,22242.0,22880.0,24148.0,24439.0,26225.0,27206.0,28666.0,29719.0
9,E10000015,Hertfordshire,13389.0,13978.0,14230.0,15246.0,16179.0,16519.0,17100.0,17498.0,...,21801.0,21839.0,22851.0,23716.0,24246.0,24552.0,25519.0,27765.0,29461.0,31193.0
10,E10000016,Kent,11515.0,12288.0,12661.0,13482.0,14013.0,14536.0,15042.0,15590.0,...,19397.0,19591.0,20332.0,21723.0,21975.0,21973.0,23384.0,24902.0,27084.0,27587.0
11,E10000017,Lancashire,11427.0,11808.0,11937.0,12705.0,12904.0,13418.0,14048.0,14531.0,...,18805.0,19041.0,19550.0,20214.0,21236.0,20999.0,22547.0,24206.0,26150.0,27356.0

================================================================================
Sheet: 4c
================================================================================

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
0,Table 4c - Ratio of lower quartile house price...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Code,Name,1997.00,1998.00,1999.00,2000.00,2001.00,2002.00,2003.00,2004.00,...,2017.00,2018.00,2019.00,2020.00,2021.00,2022.00,2023.00,2024.00,2025.00,5-Year Average
2,E10000003,Cambridgeshire,3.80,3.89,4.08,4.31,4.77,5.54,6.27,6.87,...,8.87,9.17,9.17,9.29,9.85,9.65,9.37,8.68,8.35,9.18
3,E10000007,Derbyshire,3.14,3.30,3.29,3.29,3.40,3.87,4.60,5.72,...,6.65,6.61,6.71,6.43,7.10,7.17,7.19,6.53,6.37,6.87
4,E10000008,Devon,4.30,4.40,4.55,4.91,5.40,6.52,8.02,9.05,...,9.58,9.54,9.32,9.75,10.40,10.35,10.11,9.12,8.60,9.72
5,E10000011,East Sussex,4.07,4.08,4.37,4.44,5.08,6.09,7.22,8.19,...,10.60,10.59,10.99,10.63,11.68,10.86,10.80,9.50,9.09,10.39
6,E10000012,Essex,3.98,4.07,4.36,4.64,5.12,5.88,7.45,8.22,...,10.98,11.21,11.04,10.84,11.74,11.35,11.00,9.87,10.18,10.83
7,E10000013,Gloucestershire,3.91,3.83,4.13,4.30,4.84,5.45,6.49,7.73,...,8.40,8.36,8.63,9.04,9.91,9.31,9.39,8.65,8.08,9.07
8,E10000014,Hampshire,4.62,4.77,5.15,5.57,5.92,6.99,7.91,8.57,...,10.62,10.79,10.49,10.15,10.84,10.29,10.11,9.59,9.42,10.05
9,E10000015,Hertfordshire,4.44,4.79,5.20,5.64,6.15,7.08,8.19,8.97,...,13.05,12.91,12.37,12.58,13.24,12.74,12.01,11.37,10.90,12.05
10,E10000016,Kent,4.13,4.15,4.34,4.67,5.19,5.85,7.05,8.08,...,10.72,10.94,10.36,10.47,11.61,11.20,10.84,9.78,9.79,10.64
11,E10000017,Lancashire,3.02,2.96,3.02,2.91,2.91,2.94,3.20,4.09,...,5.50,5.37,5.44,5.32,6.07,5.59,5.45,5.16,5.12,5.48

================================================================================
Sheet: 5a
================================================================================

,0,1,2,3,4,5,6,7,8,9,...,23,24,25,26,27,28,29,30,31,32
0,Table 5a - Median house price by local authori...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Country/Region code,Country/Region name,Local authority code,Local authority name,Year ending Sep 1997,Year ending Sep 1998,Year ending Sep 1999,Year ending Sep 2000,Year ending Sep 2001,Year ending Sep 2002,...,Year ending Sep 2016,Year ending Sep 2017,Year ending Sep 2018,Year ending Sep 2019,Year ending Sep 2020,Year ending Sep 2021,Year ending Sep 2022,Year ending Sep 2023,Year ending Sep 2024,Year ending Sep 2025
2,E12000001,North East,E06000001,Hartlepool,41500,44250,46000,47500,47500,53000,...,120000,122975,124000,129950,130000,140000,140000,152750,151000,155000
3,E12000001,North East,E06000002,Middlesbrough,45000,42000,46500,45000,44500,47583,...,131000,125000,133000,134995,135000,140500,147500,150000,153000,153500
4,E12000001,North East,E06000003,Redcar and Cleveland,44995,45950,45000,49000,52000,56000,...,130000,130000,133750,130000,134995,145000,150000,159000,165000,165000
5,E12000001,North East,E06000004,Stockton-on-Tees,49950,49995,52500,55500,58995,65000,...,135000,142500,146000,147000,152975,161250,160000,175000,175000,175000
6,E12000001,North East,E06000005,Darlington,46950,50000,50000,52000,55000,59000,...,133000,137975,139000,140500,150000,162000,160000,167500,165000,178000
7,E12000001,North East,E06000047,County Durham,42000,43000,45500,48000,47625,50000,...,111000,114000,116995,120995,120000,135000,130000,130600,137000,143000
8,E12000001,North East,E06000057,Northumberland,52000,54000,58000,59950,62000,69000,...,157500,159950,165000,169000,170000,195000,182972,204950,210000,202500
9,E12000001,North East,E08000021,Newcastle upon Tyne,49000,52000,56400,58750,63000,75000,...,155000,156000,160000,164972,165000,186100,190000,204995,195000,208921
10,E12000001,North East,E08000022,North Tyneside,50675,52500,55000,55950,57000,60000,...,155000,165000,169500,174000,172250,185000,185000,198500,193000,210000
11,E12000001,North East,E08000023,South Tyneside,45000,44650,46950,48000,48950,50850,...,131950,133000,137000,136000,135000,150000,147748,155000,158342,165000

================================================================================
Sheet: 5b
================================================================================

,0,1,2,3,4,5,6,7,8,9,...,23,24,25,26,27,28,29,30,31,32
0,Table 5b - Median gross annual workplace-based...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Country/Region code,Country/Region name,Local authority code,Local authority name,1997,1998,1999,2000,2001,2002,...,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0,2023.0,2024.0,2025.0
2,E12000001,North East,E06000001,Hartlepool,15747,16149,16121,15743,17264,18251,...,26112.0,25638.0,25729.0,26010.0,28093.0,28332.0,30114.0,32313.0,32917.0,32302.0
3,E12000001,North East,E06000002,Middlesbrough,15914,15319,16073,16513,17273,19252,...,25722.0,25626.0,25170.0,26203.0,27005.0,25922.0,29777.0,31631.0,31865.0,34000.0
4,E12000001,North East,E06000003,Redcar and Cleveland,19206,18747,21274,22135,21763,20806,...,24496.0,25456.0,26170.0,25846.0,26220.0,24821.0,26462.0,30565.0,30649.0,35278.0
5,E12000001,North East,E06000004,Stockton-on-Tees,16838,17062,17199,18147,19186,18392,...,26884.0,25258.0,26540.0,29049.0,30531.0,29026.0,30643.0,30520.0,31345.0,36599.0
6,E12000001,North East,E06000005,Darlington,15424,14453,15915,16043,17220,18568,...,27009.0,25712.0,26043.0,27888.0,28045.0,29280.0,30357.0,30749.0,34376.0,33840.0
7,E12000001,North East,E06000047,County Durham,[x],[x],[x],[x],[x],[x],...,24188.0,25105.0,25810.0,26378.0,26609.0,26219.0,27737.0,29384.0,31421.0,32945.0
8,E12000001,North East,E06000057,Northumberland,[x],[x],[x],[x],[x],[x],...,25177.0,24927.0,25052.0,25773.0,27015.0,27681.0,29686.0,30939.0,32359.0,35323.0
9,E12000001,North East,E08000021,Newcastle upon Tyne,15924,15825,16988,19504,19070,19004,...,26839.0,28501.0,27813.0,28911.0,29709.0,30705.0,31808.0,33817.0,35212.0,36726.0
10,E12000001,North East,E08000022,North Tyneside,14923,15575,15701,16962,17600,18123,...,25309.0,26174.0,27701.0,28850.0,27460.0,27306.0,30078.0,31574.0,35637.0,37005.0
11,E12000001,North East,E08000023,South Tyneside,15116,16420,17114,17345,18617,18358,...,22405.0,23226.0,23620.0,24458.0,26767.0,24802.0,27826.0,28263.0,32453.0,31604.0

================================================================================
Sheet: 5c
================================================================================

,0,1,2,3,4,5,6,7,8,9,...,24,25,26,27,28,29,30,31,32,33
0,Table 5c - Ratio of median house price to medi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Country/Region code,Country/Region name,Local authority code,Local authority name,1997,1998,1999,2000,2001,2002,...,2017.00,2018.00,2019.00,2020.00,2021.00,2022.00,2023.00,2024.00,2025.00,5-Year Average
2,E12000001,North East,E06000001,Hartlepool,2.64,2.74,2.85,3.02,2.75,2.9,...,4.80,4.82,5.00,4.63,4.94,4.65,4.73,4.59,4.80,4.74
3,E12000001,North East,E06000002,Middlesbrough,2.83,2.74,2.89,2.73,2.58,2.47,...,4.88,5.28,5.15,5.00,5.42,4.95,4.74,4.80,4.51,4.88
4,E12000001,North East,E06000003,Redcar and Cleveland,2.34,2.45,2.12,2.21,2.39,2.69,...,5.11,5.11,5.03,5.15,5.84,5.67,5.20,5.38,4.68,5.35
5,E12000001,North East,E06000004,Stockton-on-Tees,2.97,2.93,3.05,3.06,3.07,3.53,...,5.64,5.50,5.06,5.01,5.56,5.22,5.73,5.58,4.78,5.37
6,E12000001,North East,E06000005,Darlington,3.04,3.46,3.14,3.24,3.19,3.18,...,5.37,5.34,5.04,5.35,5.53,5.27,5.45,4.80,5.26,5.26
7,E12000001,North East,E06000047,County Durham,[x],[x],[x],[x],[x],[x],...,4.54,4.53,4.59,4.51,5.15,4.69,4.44,4.36,4.34,4.6
8,E12000001,North East,E06000057,Northumberland,[x],[x],[x],[x],[x],[x],...,6.42,6.59,6.56,6.29,7.04,6.16,6.62,6.49,5.73,6.41
9,E12000001,North East,E08000021,Newcastle upon Tyne,3.08,3.29,3.32,3.01,3.3,3.95,...,5.47,5.75,5.71,5.55,6.06,5.97,6.06,5.54,5.69,5.86
10,E12000001,North East,E08000022,North Tyneside,3.4,3.37,3.5,3.3,3.24,3.31,...,6.30,6.12,6.03,6.27,6.78,6.15,6.29,5.42,5.67,6.06
11,E12000001,North East,E08000023,South Tyneside,2.98,2.72,2.74,2.77,2.63,2.77,...,5.73,5.80,5.56,5.04,6.05,5.31,5.48,4.88,5.22,5.39

================================================================================
Sheet: 6a
================================================================================

,0,1,2,3,4,5,6,7,8,9,...,23,24,25,26,27,28,29,30,31,32
0,Table 6a - Lower quartile house price by local...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Country/Region code,Country/Region name,Local authority code,Local authority name,Year ending Sep 1997,Year ending Sep 1998,Year ending Sep 1999,Year ending Sep 2000,Year ending Sep 2001,Year ending Sep 2002,...,Year ending Sep 2016,Year ending Sep 2017,Year ending Sep 2018,Year ending Sep 2019,Year ending Sep 2020,Year ending Sep 2021,Year ending Sep 2022,Year ending Sep 2023,Year ending Sep 2024,Year ending Sep 2025
2,E12000001,North East,E06000001,Hartlepool,25500,27000,26000,27500,25950,27708,...,70000,75625,77500,83875,83250,85000,85000,93000,92953,100000
3,E12000001,North East,E06000002,Middlesbrough,28000,27000,28500,27000,23000,25000,...,83625,79375,83000,85000,87000,90000,93000,93000,100000,105000
4,E12000001,North East,E06000003,Redcar and Cleveland,32000,34000,33000,35500,36750,37000,...,92000,90000,93875,91000,96500,105000,105000,112000,116000,124225
5,E12000001,North East,E06000004,Stockton-on-Tees,36500,36500,37000,38050,39000,41500,...,98995,105000,105000,106375,110000,119984,116750,125000,125000,128000
6,E12000001,North East,E06000005,Darlington,32000,32500,32500,35000,36000,36950,...,87500,95000,94500,95000,102000,112000,110000,115000,120000,127500
7,E12000001,North East,E06000047,County Durham,29000,29000,30000,31000,31000,32000,...,69000,69950,72000,75000,72000,81000,84000,85000,85000,92500
8,E12000001,North East,E06000057,Northumberland,34950,35000,37000,38000,38500,40000,...,105000,107500,110000,114000,115000,130000,124995,135000,138500,139988
9,E12000001,North East,E08000021,Newcastle upon Tyne,36000,36500,38500,39000,40000,46000,...,112000,114995,115249,119000,115000,133000,135000,140000,140000,150000
10,E12000001,North East,E08000022,North Tyneside,35000,35000,36000,37500,36500,40000,...,109450,113000,116900,118000,120000,125000,130000,137000,137250,147500
11,E12000001,North East,E08000023,South Tyneside,31950,31500,32000,33000,34000,35950,...,91000,90000,91500,94125,92873,107500,102000,110000,115000,119485

================================================================================
Sheet: 6b
================================================================================

,0,1,2,3,4,5,6,7,8,9,...,23,24,25,26,27,28,29,30,31,32
0,Table 6b - Lower quartile gross annual workpla...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Country/Region code,Country/Region name,Local authority code,Local authority name,1997,1998,1999,2000,2001,2002,...,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0,2023.0,2024.0,2025.0
2,E12000001,North East,E06000001,Hartlepool,11354,10180,10835,10507,11655,11598,...,20386.0,19470.0,18506.0,19238.0,19798.0,21084.0,20916.0,22081.0,24505.0,26716.0
3,E12000001,North East,E06000002,Middlesbrough,11182,11395,11649,11954,12380,12894,...,19032.0,19026.0,19076.0,20806.0,20367.0,21173.0,22989.0,23879.0,25884.0,27262.0
4,E12000001,North East,E06000003,Redcar and Cleveland,12606,12152,14000,14942,14048,14463,...,16684.0,17676.0,18340.0,19126.0,19445.0,19376.0,19662.0,23182.0,24547.0,27486.0
5,E12000001,North East,E06000004,Stockton-on-Tees,11896,11213,11622,12736,13904,12896,...,19180.0,19199.0,19178.0,21060.0,22381.0,22187.0,23635.0,24522.0,25378.0,27342.0
6,E12000001,North East,E06000005,Darlington,10206,10237,11743,11800,12104,12916,...,20244.0,18779.0,20170.0,20180.0,19319.0,20616.0,21773.0,22919.0,25108.0,27445.0
7,E12000001,North East,E06000047,County Durham,[x],[x],[x],[x],[x],[x],...,18029.0,18635.0,19532.0,19845.0,19869.0,20006.0,21879.0,22943.0,25154.0,27003.0
8,E12000001,North East,E06000057,Northumberland,[x],[x],[x],[x],[x],[x],...,17999.0,18918.0,19819.0,20085.0,19988.0,21424.0,22906.0,24051.0,25074.0,27330.0
9,E12000001,North East,E08000021,Newcastle upon Tyne,11656,11808,12272,13853,13672,13896,...,19367.0,20875.0,20034.0,20698.0,21484.0,22732.0,23758.0,26071.0,27203.0,29211.0
10,E12000001,North East,E08000022,North Tyneside,10910,10670,11555,12288,12727,13340,...,19096.0,19453.0,20200.0,22130.0,22066.0,21394.0,22220.0,24799.0,26031.0,27342.0
11,E12000001,North East,E08000023,South Tyneside,11458,12215,12527,12847,13791,13322,...,18930.0,18238.0,18361.0,18308.0,19031.0,18806.0,20427.0,21908.0,23898.0,25016.0

================================================================================
Sheet: 6c
================================================================================

,0,1,2,3,4,5,6,7,8,9,...,24,25,26,27,28,29,30,31,32,33
0,Table 6c - Ratio of lower quartile house price...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Country/Region code,Country/Region name,Local authority code,Local authority name,1997,1998,1999,2000,2001,2002,...,2017.00,2018.00,2019.00,2020.00,2021.00,2022.00,2023.00,2024.00,2025.00,5-Year Average
2,E12000001,North East,E06000001,Hartlepool,2.25,2.65,2.4,2.62,2.23,2.39,...,3.88,4.19,4.36,4.20,4.03,4.06,4.21,3.79,3.74,3.97
3,E12000001,North East,E06000002,Middlesbrough,2.5,2.37,2.45,2.26,1.86,1.94,...,4.17,4.35,4.09,4.27,4.25,4.05,3.89,3.86,3.85,3.98
4,E12000001,North East,E06000003,Redcar and Cleveland,2.54,2.8,2.36,2.38,2.62,2.56,...,5.09,5.12,4.76,4.96,5.42,5.34,4.83,4.73,4.52,4.97
5,E12000001,North East,E06000004,Stockton-on-Tees,3.07,3.26,3.18,2.99,2.8,3.22,...,5.47,5.48,5.05,4.91,5.41,4.94,5.10,4.93,4.68,5.01
6,E12000001,North East,E06000005,Darlington,3.14,3.17,2.77,2.97,2.97,2.86,...,5.06,4.69,4.71,5.28,5.43,5.05,5.02,4.78,4.65,4.99
7,E12000001,North East,E06000047,County Durham,[x],[x],[x],[x],[x],[x],...,3.75,3.69,3.78,3.62,4.05,3.84,3.70,3.38,3.43,3.68
8,E12000001,North East,E06000057,Northumberland,[x],[x],[x],[x],[x],[x],...,5.68,5.55,5.68,5.75,6.07,5.46,5.61,5.52,5.12,5.56
9,E12000001,North East,E08000021,Newcastle upon Tyne,3.09,3.09,3.14,2.82,2.93,3.31,...,5.51,5.75,5.75,5.35,5.85,5.68,5.37,5.15,5.14,5.44
10,E12000001,North East,E08000022,North Tyneside,3.21,3.28,3.12,3.05,2.87,3,...,5.81,5.79,5.33,5.44,5.84,5.85,5.52,5.27,5.39,5.57
11,E12000001,North East,E08000023,South Tyneside,2.79,2.58,2.55,2.57,2.47,2.7,...,4.93,4.98,5.14,4.88,5.72,4.99,5.02,4.81,4.78,5.06

## Candidate data table detection

The scan below searches the top of each sheet for terms likely to appear in the affordability table. It acts as a profiling aid rather than a substitute for analytical judgement.

In [5]:
def normalise_text(value):
    if pd.isna(value):
        return ""
    return re.sub(r"\s+", " ", str(value)).strip().lower()

search_terms = ["lower quartile", "median", "earnings", "ratio", "area", "local authority"]
sheet_matches = []
header_candidates = []

for sheet_name in excel_file.sheet_names:
    preview = pd.read_excel(RAW_FILE, sheet_name=sheet_name, header=None, nrows=40, dtype=str)
    sheet_text = " ".join(preview.fillna("").astype(str).to_numpy().ravel()).lower()
    matched_terms = [term for term in search_terms if term in sheet_text]
    sheet_matches.append({
        "sheet_name": sheet_name,
        "matched_terms": ", ".join(matched_terms),
        "match_count": len(matched_terms),
    })

    for row_number, row in preview.iterrows():
        row_text = " | ".join(normalise_text(value) for value in row.tolist() if normalise_text(value))
        score = sum(term in row_text for term in ["area", "code", "year", "median", "lower", "quartile", "earnings", "ratio"])
        if score >= 3:
            header_candidates.append({
                "sheet_name": sheet_name,
                "zero_based_row": row_number,
                "excel_row": row_number + 1,
                "score": score,
                "row_text": row_text[:300],
            })

sheet_match_summary = pd.DataFrame(sheet_matches).sort_values(["match_count", "sheet_name"], ascending=[False, True])
header_candidates_df = pd.DataFrame(header_candidates).sort_values(["score", "sheet_name", "excel_row"], ascending=[False, True, True])

display(sheet_match_summary)
display(header_candidates_df.head(20))

,sheet_name,matched_terms,match_count
1,Metadata,"lower quartile, median, earnings, ratio, area,...",6
0,Contents,"lower quartile, median, earnings, ratio, local...",5
17,5c,"median, earnings, ratio, local authority",4
20,6c,"lower quartile, earnings, ratio, local authority",4
5,1c,"median, earnings, ratio",3
8,2c,"lower quartile, earnings, ratio",3
11,3c,"median, earnings, ratio",3
14,4c,"lower quartile, earnings, ratio",3
16,5b,"median, earnings, local authority",3
19,6b,"lower quartile, earnings, local authority",3
4,1b,"median, earnings",2
7,2b,"lower quartile, earnings",2
10,3b,"median, earnings",2
13,4b,"lower quartile, earnings",2
15,5a,"median, local authority",2
18,6a,"lower quartile, local authority",2
3,1a,median,1
6,2a,lower quartile,1
9,3a,median,1
12,4a,lower quartile,1
2,Terms and Conditions,,0

,sheet_name,zero_based_row,excel_row,score,row_text
12,Metadata,1,2,7,affordability ratios calculated by dividing ho...
18,2c,0,1,4,table 2c - ratio of lower quartile house price...
22,4c,0,1,4,table 4c - ratio of lower quartile house price...
26,6c,0,1,4,table 6c - ratio of lower quartile house price...
3,Contents,10,11,4,table 2c (lower quartile affordability ratio) ...
7,Contents,18,19,4,table 4c (lower quartile affordability ratio) ...
11,Contents,26,27,4,table 6c (lower quartile affordability ratio) ...
14,Metadata,15,16,4,by dividing the house price for a given area b...
15,1c,0,1,3,table 1c - ratio of median house price to medi...
16,2a,0,1,3,table 2a - lower quartile house price by count...
17,2b,0,1,3,table 2b - lower quartile gross annual workpla...
19,3c,0,1,3,table 3c - ratio of median house price to medi...
20,4a,0,1,3,table 4a - lower quartile house price by count...
21,4b,0,1,3,table 4b - lower quartile gross annual workpla...
23,5c,0,1,3,table 5c - ratio of median house price to medi...
24,6a,0,1,3,table 6a - lower quartile house price by local...
25,6b,0,1,3,table 6b - lower quartile gross annual workpla...
0,Contents,6,7,3,table 1c (median affordability ratio) | ratio ...
1,Contents,8,9,3,table 2a (lower quartile house price) | lower ...
2,Contents,9,10,3,table 2b (lower quartile earnings) | lower qua...

## Initial data profile

The highest-scoring candidate is loaded as a structured first pass. The selected sheet and header row remain visible for review before the cleaning stage.

In [6]:
if not header_candidates_df.empty:
    best_candidate = header_candidates_df.iloc[0]
    DATA_SHEET = best_candidate["sheet_name"]
    HEADER_ROW = int(best_candidate["zero_based_row"])
else:
    DATA_SHEET = excel_file.sheet_names[0]
    HEADER_ROW = 0

print(f"Selected sheet: {DATA_SHEET}")
print(f"Selected header row: {HEADER_ROW} zero-based, Excel row {HEADER_ROW + 1}")

raw_df = pd.read_excel(RAW_FILE, sheet_name=DATA_SHEET, header=HEADER_ROW)
print(f"Rows: {raw_df.shape[0]:,}")
print(f"Columns: {raw_df.shape[1]:,}")
raw_df.head()

Selected sheet: Metadata
Selected header row: 1 zero-based, Excel row 2
Rows: 24
Columns: 1

  Affordability ratios calculated by dividing house prices by gross annual earnings, based on the median and lower quartiles of both house prices and earnings. The earnings data are from the Annual Survey of Hours and Earnings which provides a snapshot of earnings at April in each year. Earnings relate to gross full-time individual earnings on a place of work basis. The house price statistics come from the House Price Statistics for Small Areas, which report the median and lower quartile price paid for residential property and refer to a 12 month period with April in the middle (year ending September). Statistics are available at country, region, county and local authority district level in England and Wales.
0  For detailed information on aspects of the qua...
1     Housing affordability in England and Wales QMI
2                                           Earnings
3  Earnings data are taken from the Annual Survey...
4  • full-time earnings;\n• annual earnings where...

In [7]:
column_profile = pd.DataFrame({
    "column_name": raw_df.columns.astype(str),
    "dtype": [str(dtype) for dtype in raw_df.dtypes],
    "non_null_count": raw_df.notna().sum().values,
    "missing_count": raw_df.isna().sum().values,
    "missing_pct": (raw_df.isna().mean().values * 100).round(2),
})

duplicate_row_count = raw_df.duplicated().sum()
print(f"Exact duplicate rows: {duplicate_row_count:,}")
display(column_profile)

Exact duplicate rows: 1

,column_name,dtype,non_null_count,missing_count,missing_pct
0,Affordability ratios calculated by dividing ho...,object,24,0,0.0

In [8]:
profile_output = CLEANED_DIR / "initial_column_profile.csv"
source_record_output = RAW_DIR / "source_record.csv"

column_profile.to_csv(profile_output, index=False)
source_record.to_csv(source_record_output, index=False)

print(f"Saved column profile to: {profile_output.relative_to(PROJECT_ROOT)}")
print(f"Saved source record to: {source_record_output.relative_to(PROJECT_ROOT)}")

Saved column profile to: data\cleaned\initial_column_profile.csv
Saved source record to: data\raw\source_record.csv

## Profiling summary and next analytical step

The next notebook will clean and reshape the data after confirming the correct data sheet, area fields, year field, lower-quartile measures and row granularity.

Unusual values remain part of the review at this stage. The most unaffordable areas may look like outliers, but they are likely to be analytically important rather than errors.